---
name: OBGYN
author: Tom Hermans
url: "http://tomhermans.com/"
description: "Gynaecologiepraktijk Obgyn Antwerpen. Dr. Tina Vanderheyden &amp; Dr.Ben De Becker. Gynaecologie. Prenatale diagnostiek en hoogrisico verloskunde"
canonical: "https://gynaecologieantwerpen.be"
robots: "index,nofollow"